# Generated by Django 4.1 on 2022-08-30 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpo', models.IntegerField(unique=True)),
                ('region', models.CharField(choices=[('1', 'Bishkek'), ('2', 'Osh city'), ('3', 'Batken'), ('4', 'Djalal-Abad'), ('5', 'Naryn'), ('6', 'Osh'), ('7', 'Talas'), ('8', 'Chui'), ('9', 'IK')], max_length=222)),
                ('employees', models.CharField(max_length=100)),
                ('state_or_private', models.CharField(choices=[('1', 'государственная'), ('2', 'частная')], max_length=222)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=222)),
                ('pin_code', models.CharField(max_length=14)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=222)),
                ('pin_code', models.CharField(max_length=14)),
                ('age', models.IntegerField()),
                ('phone_number', models.CharField(max_length=25)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dr', models.CharField(choices=[('1', 'терапевт'), ('2', 'хирург')], max_length=222)),
                ('full_name', models.CharField(max_length=222)),
                ('pin_code', models.CharField(max_length=14)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('phone_number', models.CharField(max_length=25)),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Chief_Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=222)),
                ('pin_code', models.CharField(max_length=14)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('phone_number', models.CharField(max_length=25)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('nurse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.nurse')),
            ],
        ),
    ]
